// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChecRANtjRnQHsN9vk-NcUSlWOgf_w_gc',
    appId: '1:783311089966:web:52a3a47ccc349c87b10abf',
    messagingSenderId: '783311089966',
    projectId: 'news-95e6a',
    authDomain: 'news-95e6a.firebaseapp.com',
    storageBucket: 'news-95e6a.firebasestorage.app',
    measurementId: 'G-976MSL6F3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCujIEI0BH_hxyRS-xwjNrZMZhXzk9AqU',
    appId: '1:783311089966:android:746d721899ca11e0b10abf',
    messagingSenderId: '783311089966',
    projectId: 'news-95e6a',
    storageBucket: 'news-95e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcgh0pLYkoVezOEJ4h0fykRvXNTNbBjJI',
    appId: '1:783311089966:ios:30f5a0d8395a5494b10abf',
    messagingSenderId: '783311089966',
    projectId: 'news-95e6a',
    storageBucket: 'news-95e6a.firebasestorage.app',
    iosClientId: '783311089966-h0i6bjehg8g1h0ne6eq53vqv4tmc67cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcgh0pLYkoVezOEJ4h0fykRvXNTNbBjJI',
    appId: '1:783311089966:ios:30f5a0d8395a5494b10abf',
    messagingSenderId: '783311089966',
    projectId: 'news-95e6a',
    storageBucket: 'news-95e6a.firebasestorage.app',
    iosClientId: '783311089966-h0i6bjehg8g1h0ne6eq53vqv4tmc67cf.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
